Algoritmo "Soma, multiplica, subtrai e divide dois numeros"

Var
a, b,soma, multi, sub: inteiro;
di: real;
nome: caractere;

Inicio
nome<-"Netto"
escreva ("Digite um numero: ")
leia(a)
escreva ("Digite outro numero: ")
leia(b)
soma<-a+b
multi<-a*b
sub<-a-b
di<-a/b
escreval("A soma: ", soma)
escreval("A subtracao: ", sub)
escreval("A multiplicacaoo: ", multi)
escreval("A divisao: ", di)
escreval("Desenvolvido por: ", nome)

FIMALGORITMO